import { useState, useEffect } from "react"
import {
  Download, ArrowUpRight, ArrowDownRight, TrendingUp, TrendingDown
} from "lucide-react"
import {
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, PieChart, Pie, Cell, Legend, BarChart, Bar
} from "recharts"
import Sidebar from "../../components/Sidebar"
import TopBar from "../../components/Topbar"
import { transactionAPI } from "../../services/api"
import { LoadingSpinner, ErrorMessage } from "../../hooks/useApi"

// ── Constants ──────────────────────────────────────────────────────────────
const CATEGORY_COLORS = {
  Food: "#f59e0b", Rent: "#a78bfa", Travel: "#06b6d4",
  Entertainment: "#ec4899", Shopping: "#7c3aed", Health: "#10b981",
  Utilities: "#6b7280", Education: "#34d399", Others: "#9ca3af", Income: "#34d399"
}
const COLOR_LIST = ["#a78bfa","#f59e0b","#06b6d4","#ec4899","#7c3aed","#10b981","#6b7280","#34d399"]

// ── Month helpers ──────────────────────────────────────────────────────────
function getAvailableMonths(count = 6) {
  const months = []
  const now = new Date()
  for (let i = 0; i < count; i++) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1)
    const value = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`
    const label = d.toLocaleString("default", { month: "long", year: "numeric" })
    months.push({ value, label })
  }
  return months
}

// ── Tooltips ───────────────────────────────────────────────────────────────
function LineTooltip({ active, payload, label }) {
  if (!active || !payload?.length) return null
  return (
    <div style={{ background: "#13102a", border: "1px solid rgba(124,58,237,0.3)", borderRadius: 10, padding: "10px 14px" }}>
      <div style={{ color: "#9ca3af", fontSize: 12, marginBottom: 6 }}>{label}</div>
      {payload.map(p => (
        <div key={p.name} style={{ fontSize: 13, fontWeight: 600, color: p.name === "income" ? "#34d399" : "#f87171", marginBottom: 2 }}>
          {p.name === "income" ? "Income" : "Expense"}: ₹{p.value.toLocaleString()}
        </div>
      ))}
    </div>
  )
}

function WeeklyTooltip({ active, payload, label }) {
  if (!active || !payload?.length) return null
  return (
    <div style={{ background: "#13102a", border: "1px solid rgba(124,58,237,0.3)", borderRadius: 10, padding: "10px 14px" }}>
      <div style={{ color: "#9ca3af", fontSize: 12, marginBottom: 4 }}>{label}</div>
      <div style={{ fontSize: 13, fontWeight: 600, color: "#a78bfa" }}>₹{payload[0].value.toLocaleString()}</div>
    </div>
  )
}

function CustomLegend({ payload }) {
  return (
    <div style={{ display: "flex", flexWrap: "wrap", gap: "8px 16px", justifyContent: "center", marginTop: 8 }}>
      {payload.map(({ value, color }) => (
        <div key={value} style={{ display: "flex", alignItems: "center", gap: 6 }}>
          <div style={{ width: 8, height: 8, borderRadius: "50%", background: color }} />
          <span style={{ fontSize: 12, color: "#9ca3af" }}>{value}</span>
        </div>
      ))}
    </div>
  )
}

// ── Export to PDF ──────────────────────────────────────────────────────────
function exportPDF(month, summary, tableData, trendData) {
  const savingsRate = summary.income > 0 ? Math.round((summary.savings / summary.income) * 100) : 0
  const content = `
SpendWise — Monthly Report
Month: ${month}
Generated: ${new Date().toLocaleDateString("en-IN")}

─────────────────────────────
SUMMARY
─────────────────────────────
Total Income:   ₹${(summary.income || 0).toLocaleString()}
Total Expenses: ₹${(summary.expense || 0).toLocaleString()}
Net Savings:    ₹${(summary.savings || 0).toLocaleString()}
Savings Rate:   ${savingsRate}%

─────────────────────────────
MONTHLY TREND (Last 6 Months)
─────────────────────────────
${trendData.map(d => `${d.month.padEnd(5)} | Income: ₹${d.income.toLocaleString().padStart(8)} | Expense: ₹${d.expense.toLocaleString().padStart(8)}`).join("\n")}

─────────────────────────────
MONTHLY BREAKDOWN TABLE
─────────────────────────────
${tableData.map(r => `${r.label.padEnd(18)} | Income: ₹${r.income.toLocaleString().padStart(8)} | Expense: ₹${r.expense.toLocaleString().padStart(8)} | Savings: ₹${r.savings.toLocaleString().padStart(8)}`).join("\n")}

─────────────────────────────
Generated by SpendWise © 2026
  `.trim()

  const blob = new Blob([content], { type: "text/plain" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `SpendWise_Report_${month.replace(/ /g, "_")}.txt`
  a.click()
  URL.revokeObjectURL(url)
}

// ── Main Reports Page ──────────────────────────────────────────────────────
export default function Reports() {
  const availableMonths = getAvailableMonths(6)
  const [selectedMonth, setSelectedMonth] = useState(availableMonths[0].value)

  const [summary, setSummary]       = useState({ income: 0, expense: 0, savings: 0, savingsRate: 0 })
  const [trendData, setTrendData]   = useState([])
  const [categoryData, setCategoryData] = useState([])
  const [weeklyData, setWeeklyData] = useState([])
  const [tableData, setTableData]   = useState([])
  const [pageLoading, setPageLoading] = useState(true)
  const [pageError, setPageError]     = useState(null)

  useEffect(() => {
    fetchReportData()
  }, [selectedMonth])

  const fetchReportData = async () => {
    setPageLoading(true)
    setPageError(null)
    try {
      // ── Fetch summary for selected month ──
      const summaryRes = await transactionAPI.getSummary(selectedMonth)
      const s = summaryRes.data
      const savings = (s.income || 0) - (s.expense || 0)
      const savingsRate = s.income > 0 ? Math.round((savings / s.income) * 100) : 0
      setSummary({ ...s, savings, savingsRate })

      // ── Fetch all transactions for this month ──
      const [year, m] = selectedMonth.split("-")
      const from = `${year}-${m}-01`
      const lastDay = new Date(year, m, 0).getDate()
      const to = `${year}-${m}-${String(lastDay).padStart(2, "0")}`
      const txRes = await transactionAPI.getAll({ from, to })
      const txs = txRes.data

      // ── Build category pie data ──
      const catMap = {}
      txs.filter(t => t.type === "expense").forEach(t => {
        catMap[t.category] = (catMap[t.category] || 0) + t.amount
      })
      const pieData = Object.entries(catMap).map(([name, value], i) => ({
        name, value, color: CATEGORY_COLORS[name] || COLOR_LIST[i % COLOR_LIST.length]
      }))
      setCategoryData(pieData)

      // ── Build weekly breakdown ──
      const weeks = [
        { week: "Week 1", amount: 0 },
        { week: "Week 2", amount: 0 },
        { week: "Week 3", amount: 0 },
        { week: "Week 4", amount: 0 },
      ]
      txs.filter(t => t.type === "expense").forEach(t => {
        const day = new Date(t.date).getDate()
        const weekIdx = Math.min(Math.floor((day - 1) / 7), 3)
        weeks[weekIdx].amount += t.amount
      })
      setWeeklyData(weeks)

      // ── Build 6-month trend ──
      const [selYear, selMonthNum] = selectedMonth.split("-").map(Number)
      const trend = []
      const table = []
      for (let i = 5; i >= 0; i--) {
        const d = new Date(selYear, selMonthNum - 1 - i, 1)
        const monthStr = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`
        const label = d.toLocaleString("default", { month: "short" })
        const fullLabel = d.toLocaleString("default", { month: "long", year: "numeric" })
        const res = await transactionAPI.getSummary(monthStr)
        const inc = res.data.income || 0
        const exp = res.data.expense || 0
        const sav = inc - exp
        trend.push({ month: label, income: inc, expense: exp })
        table.push({ label: fullLabel, monthKey: monthStr, income: inc, expense: exp, savings: sav })
      }
      setTrendData(trend)
      setTableData(table.reverse()) // newest first

    } catch (err) {
      setPageError(err.response?.data?.message || "Failed to load report")
    } finally {
      setPageLoading(false)
    }
  }

  const selectedMonthLabel = availableMonths.find(m => m.value === selectedMonth)?.label ?? ""
  const savingsRate = summary.income > 0 ? Math.round((summary.savings / summary.income) * 100) : 0

  const summaryCards = [
    { label: "Total Income",   value: `₹${(summary.income  || 0).toLocaleString()}`, color: "#34d399", bg: "rgba(52,211,153,0.1)",   border: "rgba(52,211,153,0.2)",   icon: ArrowUpRight,  trend: "+0%" },
    { label: "Total Expenses", value: `₹${(summary.expense || 0).toLocaleString()}`, color: "#f87171", bg: "rgba(248,113,113,0.1)",  border: "rgba(248,113,113,0.2)",  icon: ArrowDownRight, trend: "-8%" },
    { label: "Net Savings",    value: `₹${(summary.savings || 0).toLocaleString()}`, color: "#a78bfa", bg: "rgba(167,139,250,0.1)", border: "rgba(167,139,250,0.2)", icon: TrendingUp,     trend: "+12%" },
    { label: "Savings Rate",   value: `${savingsRate}%`,                              color: "#06b6d4", bg: "rgba(6,182,212,0.1)",   border: "rgba(6,182,212,0.2)",   icon: TrendingDown,   trend: "+5%" },
  ]

  if (pageLoading) return (
    <div style={{ background: "#08080f", minHeight: "100vh", fontFamily: "'DM Sans', sans-serif", display: "flex" }}>
      <Sidebar />
      <main className="main-content" style={{ marginLeft: 240, flex: 1, display: "flex", alignItems: "center", justifyContent: "center" }}>
        <LoadingSpinner />
      </main>
    </div>
  )

  if (pageError) return (
    <div style={{ background: "#08080f", minHeight: "100vh", fontFamily: "'DM Sans', sans-serif", display: "flex" }}>
      <Sidebar />
      <main className="main-content" style={{ marginLeft: 240, flex: 1, display: "flex", alignItems: "center", justifyContent: "center" }}>
        <ErrorMessage message={pageError} onRetry={fetchReportData} />
      </main>
    </div>
  )

  return (
    <div style={{ background: "#08080f", minHeight: "100vh", fontFamily: "'DM Sans', sans-serif", color: "#fff", display: "flex" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&display=swap');
        * { box-sizing: border-box; margin: 0; padding: 0; }
        @keyframes fadeUp { from{opacity:0;transform:translateY(16px)} to{opacity:1;transform:translateY(0)} }
        .page-animate { animation: fadeUp 0.5s ease; }
        .recharts-tooltip-cursor { fill: rgba(124,58,237,0.06) !important; }
        .row-hover:hover { background: rgba(255,255,255,0.03) !important; }
        select option { background: #13102a; color: #fff; }
        @media (max-width: 768px) { .main-content { margin-left: 0 !important; } }
      `}</style>

      <Sidebar />

      <main className="main-content" style={{ marginLeft: 240, flex: 1, minHeight: "100vh" }}>
        <TopBar title="Reports" subtitle="Financial overview and insights">
          <select value={selectedMonth} onChange={e => setSelectedMonth(e.target.value)}
            style={{ background: "rgba(255,255,255,0.05)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 8, color: "#d1d5db", padding: "7px 12px", fontSize: 13, cursor: "pointer", fontFamily: "'DM Sans', sans-serif" }}>
            {availableMonths.map(({ value, label }) => (
              <option key={value} value={value}>{label}</option>
            ))}
          </select>
          <button onClick={() => exportPDF(selectedMonthLabel, summary, tableData, trendData)}
            style={{ background: "linear-gradient(135deg,#7c3aed,#6d28d9)", color: "#fff", border: "none", borderRadius: 8, padding: "8px 16px", fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: "'DM Sans', sans-serif", display: "flex", alignItems: "center", gap: 6, boxShadow: "0 4px 14px rgba(124,58,237,0.3)", transition: "all 0.2s" }}
            onMouseEnter={e => e.currentTarget.style.transform = "translateY(-1px)"}
            onMouseLeave={e => e.currentTarget.style.transform = "translateY(0)"}>
            <Download size={14} /> Export Report
          </button>
        </TopBar>

        <div className="page-animate" style={{ padding: 28 }}>

          {/* ── Summary Cards ── */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px,1fr))", gap: 14, marginBottom: 24 }}>
            {summaryCards.map(({ label, value, color, bg, border, icon: Icon, trend }) => (
              <div key={label} style={{ background: bg, border: `1px solid ${border}`, borderRadius: 13, padding: "18px 20px", transition: "transform 0.2s" }}
                onMouseEnter={e => e.currentTarget.style.transform = "translateY(-2px)"}
                onMouseLeave={e => e.currentTarget.style.transform = "translateY(0)"}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 }}>
                  <span style={{ fontSize: 12, color: "#9ca3af" }}>{label}</span>
                  <div style={{ width: 30, height: 30, borderRadius: 8, background: `${color}18`, display: "flex", alignItems: "center", justifyContent: "center" }}>
                    <Icon size={14} color={color} />
                  </div>
                </div>
                <div style={{ fontSize: 22, fontWeight: 800, color, marginBottom: 4 }}>{value}</div>
                <div style={{ fontSize: 11, color: trend.startsWith("+") ? "#34d399" : "#f87171", fontWeight: 600 }}>{trend} vs last month</div>
              </div>
            ))}
          </div>

          {/* ── Charts Row 1: Line + Donut ── */}
          <div style={{ display: "grid", gridTemplateColumns: "1.6fr 1fr", gap: 16, marginBottom: 20 }}>

            {/* Line chart */}
            <div style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 14, padding: "22px 20px" }}>
              <div style={{ marginBottom: 20 }}>
                <div style={{ fontWeight: 700, fontSize: 15, marginBottom: 2 }}>Income vs Expense Trend</div>
                <div style={{ fontSize: 12, color: "#6b7280" }}>Last 6 months overview</div>
              </div>
              <div style={{ display: "flex", gap: 16, marginBottom: 16 }}>
                {[["#34d399", "Income"], ["#f87171", "Expense"]].map(([color, label]) => (
                  <div key={label} style={{ display: "flex", alignItems: "center", gap: 6 }}>
                    <div style={{ width: 20, height: 2, background: color, borderRadius: 1 }} />
                    <span style={{ fontSize: 12, color: "#9ca3af" }}>{label}</span>
                  </div>
                ))}
              </div>
              <ResponsiveContainer width="100%" height={220}>
                <LineChart data={trendData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" vertical={false} />
                  <XAxis dataKey="month" tick={{ fill: "#6b7280", fontSize: 12 }} axisLine={false} tickLine={false} />
                  <YAxis tick={{ fill: "#6b7280", fontSize: 11 }} axisLine={false} tickLine={false} tickFormatter={v => `₹${(v / 1000).toFixed(0)}k`} />
                  <Tooltip content={<LineTooltip />} />
                  <Line type="monotone" dataKey="income"  stroke="#34d399" strokeWidth={2.5} dot={{ fill: "#34d399", strokeWidth: 0, r: 4 }} activeDot={{ r: 6 }} />
                  <Line type="monotone" dataKey="expense" stroke="#f87171" strokeWidth={2.5} dot={{ fill: "#f87171", strokeWidth: 0, r: 4 }} activeDot={{ r: 6 }} />
                </LineChart>
              </ResponsiveContainer>
            </div>

            {/* Donut chart */}
            <div style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 14, padding: "22px 20px" }}>
              <div style={{ marginBottom: 8 }}>
                <div style={{ fontWeight: 700, fontSize: 15, marginBottom: 2 }}>Expense Breakdown</div>
                <div style={{ fontSize: 12, color: "#6b7280" }}>By category — {selectedMonthLabel}</div>
              </div>
              {categoryData.length === 0 ? (
                <div style={{ display: "flex", alignItems: "center", justifyContent: "center", height: 220, color: "#4b5563", fontSize: 13 }}>
                  No expense data for this month
                </div>
              ) : (
                <ResponsiveContainer width="100%" height={260}>
                  <PieChart>
                    <Pie data={categoryData} cx="50%" cy="45%" innerRadius={55} outerRadius={80} paddingAngle={3} dataKey="value">
                      {categoryData.map((entry, i) => <Cell key={i} fill={entry.color} stroke="transparent" />)}
                    </Pie>
                    <Tooltip formatter={v => [`₹${v.toLocaleString()}`, ""]} contentStyle={{ background: "#13102a", border: "1px solid rgba(124,58,237,0.3)", borderRadius: 8, fontSize: 13 }} />
                    <Legend content={<CustomLegend />} />
                  </PieChart>
                </ResponsiveContainer>
              )}
            </div>
          </div>

          {/* ── Weekly Bar ── */}
          <div style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 14, padding: "22px 20px", marginBottom: 20 }}>
            <div style={{ marginBottom: 20 }}>
              <div style={{ fontWeight: 700, fontSize: 15, marginBottom: 2 }}>Weekly Spending Breakdown</div>
              <div style={{ fontSize: 12, color: "#6b7280" }}>Total expenses per week — {selectedMonthLabel}</div>
            </div>
            <ResponsiveContainer width="100%" height={200}>
              <BarChart data={weeklyData} barSize={40}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" vertical={false} />
                <XAxis dataKey="week" tick={{ fill: "#6b7280", fontSize: 13 }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fill: "#6b7280", fontSize: 11 }} axisLine={false} tickLine={false} tickFormatter={v => `₹${(v / 1000).toFixed(0)}k`} />
                <Tooltip content={<WeeklyTooltip />} cursor={{ fill: "rgba(124,58,237,0.06)" }} />
                <Bar dataKey="amount" radius={[6, 6, 0, 0]}>
                  {weeklyData.map((entry, i) => (
                    <Cell key={i} fill={entry.amount === Math.max(...weeklyData.map(d => d.amount)) ? "#7c3aed" : "rgba(124,58,237,0.35)"} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 10, marginTop: 16 }}>
              {weeklyData.map((w, i) => (
                <div key={i} style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: 9, padding: "10px 14px", textAlign: "center" }}>
                  <div style={{ fontSize: 11, color: "#6b7280", marginBottom: 4 }}>{w.week}</div>
                  <div style={{ fontSize: 15, fontWeight: 700, color: "#a78bfa" }}>₹{w.amount.toLocaleString()}</div>
                </div>
              ))}
            </div>
          </div>

          {/* ── Monthly Summary Table ── */}
          <div style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 14, overflow: "hidden" }}>
            <div style={{ padding: "20px 22px", borderBottom: "1px solid rgba(255,255,255,0.07)" }}>
              <div style={{ fontWeight: 700, fontSize: 15, marginBottom: 2 }}>Monthly Breakdown</div>
              <div style={{ fontSize: 12, color: "#6b7280" }}>6-month summary with savings overview</div>
            </div>
            <div style={{ overflowX: "auto" }}>
              <table style={{ width: "100%", borderCollapse: "collapse", minWidth: 560 }}>
                <thead>
                  <tr style={{ background: "rgba(255,255,255,0.03)" }}>
                    {["Month", "Income", "Expenses", "Net Savings", "Savings %", "Status"].map(h => (
                      <th key={h} style={{ textAlign: "left", fontSize: 11, color: "#4b5563", fontWeight: 600, padding: "14px 18px", letterSpacing: "0.05em", whiteSpace: "nowrap" }}>{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {tableData.length === 0 ? (
                    <tr>
                      <td colSpan={6} style={{ textAlign: "center", padding: "40px", color: "#4b5563", fontSize: 13 }}>No data available</td>
                    </tr>
                  ) : tableData.map((row, i) => {
                    const rate = row.income > 0 ? Math.round((row.savings / row.income) * 100) : 0
                    const isSelected = row.monthKey === selectedMonth
                    const status = rate >= 20 ? "on-track" : "warning"
                    return (
                      <tr key={i} className="row-hover"
                        style={{ borderTop: "1px solid rgba(255,255,255,0.05)", background: isSelected ? "rgba(124,58,237,0.07)" : "transparent", transition: "background 0.2s", cursor: "pointer" }}
                        onClick={() => setSelectedMonth(row.monthKey)}>
                        <td style={{ padding: "13px 18px", fontSize: 13, fontWeight: isSelected ? 700 : 500, color: isSelected ? "#a78bfa" : "#d1d5db", whiteSpace: "nowrap" }}>
                          {isSelected && <span style={{ marginRight: 6 }}>›</span>}{row.label}
                        </td>
                        <td style={{ padding: "13px 18px", fontSize: 13, fontWeight: 600, color: "#34d399" }}>₹{row.income.toLocaleString()}</td>
                        <td style={{ padding: "13px 18px", fontSize: 13, fontWeight: 600, color: "#f87171" }}>₹{row.expense.toLocaleString()}</td>
                        <td style={{ padding: "13px 18px", fontSize: 13, fontWeight: 700, color: "#a78bfa" }}>₹{row.savings.toLocaleString()}</td>
                        <td style={{ padding: "13px 18px" }}>
                          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                            <div style={{ flex: 1, height: 4, background: "rgba(255,255,255,0.08)", borderRadius: 100, overflow: "hidden", maxWidth: 60 }}>
                              <div style={{ height: "100%", width: `${Math.min(rate, 100)}%`, background: rate >= 40 ? "#34d399" : rate >= 25 ? "#f59e0b" : "#f87171", borderRadius: 100 }} />
                            </div>
                            <span style={{ fontSize: 12, fontWeight: 600, color: rate >= 40 ? "#34d399" : rate >= 25 ? "#f59e0b" : "#f87171" }}>{rate}%</span>
                          </div>
                        </td>
                        <td style={{ padding: "13px 18px" }}>
                          <span style={{ fontSize: 11, fontWeight: 600, padding: "3px 10px", borderRadius: 100, background: status === "on-track" ? "rgba(52,211,153,0.12)" : "rgba(245,158,11,0.12)", color: status === "on-track" ? "#34d399" : "#f59e0b", border: `1px solid ${status === "on-track" ? "rgba(52,211,153,0.25)" : "rgba(245,158,11,0.25)"}` }}>
                            {status === "on-track" ? "✓ On Track" : "⚠ Watch"}
                          </span>
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
